terrafx/terrafx

- TerraFX.sln
- scripts/azure-pipelines.yml
This adds the necessary files to start running CI jobs for commits and PRs.
> Adding an azure-pipelines.yml file

- TerraFX.sln
- docs/design/Overview.md
Adding an "Overview" design document detailing the basic concepts and structure of TerraFX.
> [DOCS] Adding a basic "Overview" document

- docs/README.md
Adds CI status badges for Windows and Ubuntu16.04 for the Debug and Release configurations.
> Adding CI status badges to the README.md

- docs/design/audio.md
I've added a few design ideas and suggestions for a low-level audio API, based on my (admittedly somewhat limited) experience working with audio. Most of the notes in here are fairly brief right now because I wanted to elicit feedback on the design requirements and suggested API as an overview, rather than get too entrenched in one design.
I wasn't entirely sure whether I should have made an issue first or not, but based on what you told me on Discord I figured this would be alright.
> [DOCS] Add initial design ideas for low-level audio API

- Directory.Build.props
- TerraFX.sln
- docs/CODE_OF_CONDUCT.md
- scripts/azure-pipelines.yml
- scripts/azure-unix.yml
- scripts/azure-windows.yml
- scripts/build.ps1
- scripts/build.sh
- sources/Directory.Build.props
- sources/Directory.Build.targets
- tests/Directory.Build.props
This adds CI legs for macOS and ensures test results are published. A separate PR will add the new CI legs to the readme.
> Adding CI legs for macOS and ensuring test results are published.

- Directory.Build.props
- Directory.Build.targets
- docs/CODE_OF_CONDUCT.md
- docs/CONTRIBUTING.md
- docs/ISSUE_TEMPLATE.md
- docs/PULL_REQUEST_TEMPLATE.md
- docs/README.md
- scripts/azure-unix.yml
- scripts/azure-windows.yml
This updates the contact e-mail and adds a publish step for build artifacts.
> Updating the contact e-mail and adding a publish step for build artifacts.

- .editorconfig
- Directory.Build.props
- Directory.Build.targets
- samples/TerraFX/Graphics/EnumerateGraphicsAdapters.cs
- samples/TerraFX/Program.cs
- samples/TerraFX/Shared/Sample.cs
- scripts/azure-ci.yml
- scripts/azure-pipelines.yml
- scripts/azure-pr.yml
- scripts/azure-unix.yml
- scripts/azure-windows.yml
- scripts/build.ps1
- scripts/build.sh
- sources/ApplicationModel/Application.cs
- sources/Core/Collections/IObservableDictionary`2.cs
- sources/Core/Collections/PropertySet.cs
- sources/Core/Timestamp.cs
- sources/Provider/D3D12/Graphics/GraphicsAdapter.cs
- sources/Provider/Vulkan/Graphics/GraphicsAdapter.cs
- sources/Provider/Win32/UI/DispatchProvider.cs
- sources/Provider/Win32/UI/Dispatcher.cs
- sources/Provider/Win32/UI/Window.cs
- sources/Provider/Win32/UI/WindowProvider.cs
- sources/Provider/X11/UI/DispatchProvider.cs
- sources/Provider/X11/UI/Dispatcher.cs
- sources/Provider/X11/UI/Window.cs
- sources/Provider/X11/UI/WindowProvider.cs
This updates the dependencies to their latest versions and adds NuGet publishing support to CI.
> Updating dependencies and adding NuGet publishing support.

- sources/ApplicationModel/Application.cs
- sources/ApplicationModel/ApplicationIdleEventArgs.cs
This adds support for a basic variable refresh rate FPS counter.
> Adding basic support for tracking and reporting the number of frames per second.

- sources/Core/Collections/INotifyCollectionChanged`1.cs
- sources/Core/Collections/INotifyDictionaryChanged`2.cs
- sources/Core/PropertyChangedEventArgs`1.cs
- sources/Graphics/IGraphicsSurface.cs
- sources/Provider/D3D12/Graphics/GraphicsAdapter.cs
- sources/Provider/D3D12/Graphics/GraphicsContext.cs
- sources/Provider/Vulkan/Graphics/GraphicsContext.cs
- sources/Provider/Win32/UI/GraphicsSurface.cs
- sources/Provider/Win32/UI/Window.cs
- sources/Provider/Xlib/UI/GraphicsSurface.cs
- sources/Provider/Xlib/UI/Window.cs
- sources/UI/IWindow.cs
This updates the GraphicsSurface and GraphicsContext to better support window resizing events by exposing a SizeChanged event.
> Updating the GraphicsContext to better support window resizing.

- Directory.Build.targets
- sources/Provider/D3D12/TerraFX.Provider.D3D12.csproj
- sources/Provider/Win32/TerraFX.Provider.Win32.csproj
- sources/Provider/Win32/UI/Window.cs
- sources/Provider/Win32/UI/WindowProvider.cs
This updates the interop dependencies to their latest versions to pick up some minor optimizations in the bindings.
> Updating the interop dependencies to their latest versions.

- TerraFX.sln
- docs/README.md
This adds a link to the samples document in the readme, so newcomers to the repo can easily find it.
> Adding a link to the samples document in the readme

- Directory.Build.targets
- sources/Provider/D3D12/Graphics/GraphicsContext.cs
- sources/Provider/D3D12/Graphics/GraphicsProvider.cs
- sources/Provider/D3D12/TerraFX.Provider.D3D12.csproj
- sources/Provider/Vulkan/Graphics/GraphicsContext.cs
This cleans up the D3D12 and Vulkan graphics providers to be more consistent with eachother.
> Cleaning up the D3D12 and Vulkan providers.

- Directory.Build.targets
- sources/ApplicationModel/Application.cs
- sources/Providers/Graphics/D3D12/GraphicsContext.cs
- sources/Providers/Graphics/D3D12/GraphicsProvider.cs
- sources/Providers/Graphics/Vulkan/GraphicsContext.cs
- sources/Providers/Graphics/Vulkan/GraphicsProvider.cs
- sources/Providers/UI/Win32/DispatchProvider.cs
- sources/Providers/UI/Win32/Window.cs
- sources/Providers/UI/Win32/WindowProvider.cs
- sources/Providers/UI/Xlib/DispatchProvider.cs
- sources/Providers/UI/Xlib/Window.cs
- sources/Providers/UI/Xlib/WindowProvider.cs
- sources/Utilities/AssertionUtilities.cs
- sources/Utilities/InteropUtilities.cs
- sources/Utilities/Pointer`1.cs
- sources/Utilities/ValueLazy`1.cs
- tests/Utilities/InteropUtilities.cs
This improves several of the TerraFX.Utilities types to include additional methods/properties.
> Improving some of the TerraFX.Utilities types

- Directory.Build.targets
- scripts/build.ps1
- scripts/build.sh
This updates TerraFX to explicitly target .NET 5 Preview 1
> Explicitly target .NET 5 Preview 1

- .github/workflows/ci.yml
- Directory.Build.props
- Directory.Build.targets
- scripts/build.ps1
- scripts/build.sh
This also updates the interop dependencies to the beta1 packages from nuget.org
> Updating to .NET 5.0 GA

- samples/TerraFX/Shared/Sample.cs
Added extracting the error message from the shader compiler if compilation failed.
> [IMLP] ShaderErrorMsg

- sources/Providers/Graphics/D3D12/D3D12GraphicsPipelineSignature.cs
`D3D12_ROOT_PARAMETER.InitAsDescriptorTable` doesn't create a copy of the `D3D12_DESCRIPTOR_RANGE` so we need to ensure that there is a unique local per static sampler.
> Ensure we aren't reusing a local slot when constructing D3D12GraphicsPipelineSignature

- sources/Providers/UI/Win32/Win32Window.cs
`GetClientRect` returns coordinates at origin `(0, 0)` so they need to be adjusted before consumption.
> Ensure we adjust the client rectangle to screen coordinates

- sources/Graphics/Colors.cs
standard w3.org colors as static class `Colors`
> [IMPL] `Colors` class 

- sources/Core/Numerics/Matrix3x3.cs
- sources/Core/Numerics/Matrix4x4.cs
- sources/Core/Numerics/Quaternion.cs
- sources/Core/Numerics/Vector2.cs
- sources/Core/Numerics/Vector3.cs
- sources/Core/Numerics/Vector4.cs
- sources/Utilities/FloatUtilities.cs
- tests/Core/Numerics/Vector2Tests.cs
- tests/Core/Numerics/Vector3Tests.cs
- tests/Core/Numerics/Vector4Tests.cs
Vector*, Quaternion, and Matrix* should have more math operations implemented, such as rotation of a Vector via a Quaternion or Matrix. 
Quaternion and Matrix should also implement Inverse, Concatenation, etc.
See issues #102, #103, #104. A lot of the requested functionality there is in this PR.
> [IMPL] Vector*, Quaternion, Matrix* additions

- samples/TerraFX/Graphics/HelloSmoke.cs
HelloSmoke texture size and blurring fine tuned. Looks better now even with quickAndDirty==true
> [IMPL] HelloSmoke with better looking smoke

- sources/Core/Numerics/Matrix3x3.cs
- sources/Core/Numerics/Matrix4x4.cs
- sources/Core/Numerics/Quaternion.cs
- sources/Core/Numerics/Transform.cs
- tests/Core/Numerics/TransformTests.cs
Transform should be a struct that maps points and normals from one coordinate system to another.
It should assume that the rotation center of the source coordinate system is at it's origin.
It should map via
1) anisotropic scaling
2) rotation about (0,0,0)
3) translation.
> [IMPL] Transform

- samples/TerraFX/Graphics/HelloTexture3D.cs
[IMPL] Texture3D sample improvement.
This PR modifies the Texture3D sample to allow easy adjustment of the size of the 3D texture. With it, I was able to verify that at size of 512x512x512 loads and renders fine.
The default size is set to 64 such that RowPitch is 256, with a comment that this is the minimum allowed size.
> [IMPL] Texture3D sample with configurable texture size

- sources/Core/UnmanagedReadOnlySpan`1.cs
This resolves https://github.com/terrafx/terrafx/issues/179
> Fix UnmanagedReadOnlySpan`1 to be immutable

- Directory.Packages.props
- samples/TerraFX/Graphics/HelloTexture3D.cs
- sources/Core/Utilities/UnsafeUtilities.cs
- sources/Core/ValueLazy`1.cs
- sources/Graphics/Graphics/Advanced/GraphicsMemoryAllocator.DefaultMemoryAllocator.cs
- sources/Graphics/Graphics/Advanced/GraphicsMemoryManager.cs
- sources/Graphics/Graphics/GraphicsAdapter.cs
- sources/Graphics/Graphics/GraphicsCommandQueue.cs
- sources/Graphics/Graphics/GraphicsCopyContext.cs
- sources/Graphics/Graphics/GraphicsDevice.FeatureFlags.cs
- sources/Graphics/Graphics/GraphicsDevice.cs
- sources/Graphics/Graphics/GraphicsService.cs
- sources/Graphics/Utilities/D3D12Utilities.cs
- sources/UI/UI/UIWindow.cs
This resolves https://github.com/terrafx/terrafx/issues/208
> Add support for UMA based devices
