Directory.Build.props, scripts/build.ps1, scripts/build.sh
This updates the build scripts to pull down the .NET SDK for CI and downgrades the MicrosoftNetTestSdkPackageVersion so that tests will successfully run.
=> Updating the build scripts so CI can successfully run.

sources/Interop/Windows/um/d3d12/D3D12.cs
Previously did not work as intended (resulted in AVE). Fixed and verified with code and against d3dx12.h implementation. I don't think it needs a regression test as it was more a typo than anything meaningful as a bug.
=> [BUG] Fixed d3dx12.h MemcpySubresource method

Directory.Build.props
This adds the TerrFX package feed from Azure so nightlies can be tested.
=> Adding the terrafx package feed from azure.

sources/Audio/AudioDecoder.cs, sources/Audio/AudioEncoder.cs, sources/Audio/IAudioPlaybackDevice.cs
This is the follow-up PR to #18 you requested - I fixed the whitespace issues.
=> Fix whitespace issues in audio primitives

sources/ApplicationModel/Application.cs, sources/Graphics/IGraphicsProvider.cs, sources/Graphics/IGraphicsSurface.cs, sources/Provider/Vulkan/Graphics/GraphicsContext.cs, sources/Provider/Win32/UI/DispatchProvider.cs, sources/Provider/Win32/UI/GraphicsSurface.cs, sources/Provider/Win32/UI/Window.cs, sources/Provider/Win32/UI/WindowProvider.cs, sources/Provider/Xlib/UI/DispatchProvider.cs, sources/Provider/Xlib/UI/Dispatcher.cs, sources/Provider/Xlib/UI/GraphicsSurface.cs, sources/Provider/Xlib/UI/Window.cs, sources/Provider/Xlib/UI/WindowProvider.cs, sources/UI/IWindowProvider.cs
This cleans up both UI providers to be more in-sync with each other and ensures that they can cleanly shut down.
The Xlib provider was additionally updated to properly report errors and to listen for the WM_DELETE_WINDOW event.
=> Clean up the UI providers to ensure a clean shutdown.

Directory.Build.targets
This updates the package version for the PulseAudio, Vulkan, and Windows interop libraries to match their updated versions. This allows better tracking of what native library a given interop dependency represents.
=> Updating the package versions for several TerraFX.Interop libraries

sources/ApplicationModel/Application.cs, sources/Provider/Win32/HelperUtilities.cs, sources/Provider/Win32/UI/DispatchProvider.cs, sources/Provider/Win32/UI/Window.cs, sources/Provider/Win32/UI/WindowProvider.cs, sources/Provider/Xlib/HelperUtilities.cs, sources/Provider/Xlib/UI/DispatchProvider.cs, sources/Provider/Xlib/UI/Window.cs, sources/Provider/Xlib/UI/WindowProvider.cs, sources/UI/IWindow.cs, sources/UI/IWindowProvider.cs
This updates the WindowProvider to properly post a quit message to the dispatcher once all windows for the current thread have been destroyed.
=> Cleaning up the WindowProvider to properly post a quit message when all windows are destroyed

Directory.Build.targets, samples/TerraFX/Program.cs, scripts/build.ps1, scripts/build.sh, sources/Provider/Vulkan/Graphics/GraphicsContext.cs, sources/Provider/Vulkan/Graphics/GraphicsProvider.cs
This updates dependencies to the latest versions, namely picking up the netcoreapp3.0 stable binaries.
As a side effect, this also ends up fixing up the Vulkan provider to handle the updated bindings and fixes the samples to run on different threads to avoid state sharing across them.
=> Updating dependencies to the latest versions.

docs/project/Roadmap.md, docs/samples/Samples.md
PulseAudio is intentionally a single word with no spaces, and there was a missing space in the samples documentation.
These were what I could find on a quick skim through, I don't think there were any others though.
=> [DOCS] Fix a few typos in the docs

docs/README.md
The links were using an incorrect base directory.
=> Fixing the documentation links in the readme

Directory.Build.targets, sources/Provider/Win32/UI/Dispatcher.cs, sources/Provider/Win32/UI/Window.cs, sources/Provider/Win32/UI/WindowProvider.cs
Updates to the newer dependencies, which includes complete bindings for User32.
=> Updating the TerraFX.Interop.Windows dependencies to 10.0.15063-alpha-20190928.1

samples/TerraFX/Graphics/HelloWindow.cs, samples/TerraFX/Program.cs, samples/TerraFX/Shared/Sample.cs, sources/Provider/D3D12/Graphics/GraphicsContext.cs, sources/Provider/D3D12/Graphics/GraphicsProvider.cs, sources/Provider/Vulkan/Graphics/GraphicsContext.cs, sources/Provider/Vulkan/Graphics/GraphicsProvider.cs, sources/Provider/Vulkan/HelperUtilities.cs, sources/Provider/Win32/UI/WindowProvider.cs, sources/Provider/Xlib/UI/WindowProvider.cs
This enables the debug validation layers for the D3D12 and Vulkan providers. It also does some minimal sample cleanup to ensure cleanup is happening.
=> Adding basic debugging support to the D3D12 and Vulkan providers

.lfsconfig
Adding a .lfsconfig file which points to Azure.  This is separate from https://github.com/terrafx/terrafx/pull/48 to try and convince CI to pull from the right LFS location.
=> Adding a .lfsconfig file which points to Azure

sources/Audio/IAudioAdapter.cs
Implementation for #46.
`IAudioAdapter` has been made read only, as per our discussion.
=> [IMPL] Make IAudioAdapter read-only

samples/TerraFX/Program.cs, samples/TerraFX/Shared/Sample.cs, sources/Graphics/IGraphicsAdapter.cs, sources/Graphics/IGraphicsProvider.cs, sources/Providers/Graphics/D3D12/GraphicsAdapter.cs, sources/Providers/Graphics/D3D12/GraphicsProvider.cs, sources/Providers/Graphics/D3D12/HelperUtilities.cs, sources/Providers/Graphics/Vulkan/GraphicsAdapter.cs, sources/Providers/Graphics/Vulkan/GraphicsContext.cs, sources/Providers/Graphics/Vulkan/GraphicsProvider.cs, sources/Providers/Graphics/Vulkan/HelperUtilities.cs, sources/Providers/UI/Win32/WindowProvider.cs, sources/Providers/UI/Xlib/WindowProvider.cs, sources/Utilities/DisposeUtilities.cs, sources/Utilities/ExceptionUtilities.cs, sources/Utilities/InteropUtilities.cs, sources/Utilities/Resources.cs, sources/Utilities/Resources.resx, tests/Utilities/InteropUtilities.cs
This does some code cleanup of the IGraphicsAdapter and IGraphicsProvider implementations.
The big new feature is that `IGraphicsProvider` is now using `AppContext.GetData` and `AppContext.TryGetSwitch` to control certain behaviors.
Namely, there is now a shared switch, "TerraFX.Graphics.IGraphicsProvider.EnableDebugMode", which can be set to enable the D3D12/Vulkan debug layers in Release builds.
The Vulkan provider additional has its own data entries that are used to enable required and/or optional extensions and layers. This is being used alongside the debug mode switch for the debug extension/layer and is being used by the UI providers to enforce the required surface extensions to be enabled.
=> Cleaning up the IGraphicsAdapter and IGraphicsProvider implementations.

Directory.Build.targets, samples/TerraFX/Graphics/EnumerateGraphicsAdapters.cs, samples/TerraFX/Graphics/HelloWindow.cs, samples/TerraFX/Properties/launchSettings.json, sources/Graphics/GraphicsAdapter.cs, sources/Graphics/GraphicsContext.cs, sources/Graphics/GraphicsDevice.cs, sources/Graphics/GraphicsFence.cs, sources/Graphics/GraphicsProvider.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsAdapter.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsContext.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsFence.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsProvider.cs, sources/Providers/Graphics/D3D12/HelperUtilities.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsAdapter.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsContext.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsDevice.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsFence.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsProvider.cs, sources/Utilities/AssertionUtilities.cs, sources/Utilities/DisposeUtilities.cs, sources/Utilities/ExceptionUtilities.cs, sources/Utilities/Resources.cs, sources/Utilities/Resources.resx, sources/Utilities/ValueLazy`1.cs
This splits GraphicsContext into 3 parts:
* GraphicsDevice, which manages the overall state
* GraphicsFence, which manages fence state
* GraphicsContext, which has one instance per backbuffer and manages per frame state
=> Splitting GraphicsContext into multiple classes

samples/TerraFX/Graphics/HelloQuad.cs, samples/TerraFX/Program.cs, sources/Graphics/GraphicsBuffer.cs, sources/Graphics/GraphicsBufferKind.cs, sources/Graphics/GraphicsDevice.cs, sources/Graphics/GraphicsPrimitive.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsContext.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPipeline.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPrimitive.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsContext.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsDevice.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsPrimitive.cs, tests/Utilities/InteropUtilities.cs
This adds support for rendering indexed primitives and adds a corresponding `HelloQuad` sample.
=> Adding support for rendering indexed primitives

samples/TerraFX/Graphics/HelloQuad.cs, samples/TerraFX/Graphics/HelloTriangle.cs, sources/Graphics/GraphicsDevice.cs, sources/Graphics/GraphicsPipeline.cs, sources/Graphics/GraphicsPipelineInputElement.cs, sources/Graphics/GraphicsPipelineInputElementKind.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPipeline.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsBuffer.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsDevice.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsPipeline.cs
This adds a new `GraphicsPipelineInputElement` type which can be used to describe the layout of the input to the vertex shader. The recognized types are currently fairly limited but will be expanded as other functionality comes online.
=> Adding a GraphicsPipelineInputElement type

Directory.Build.targets
This upgrades the various interop libraries to the respective alpha-20191220.1 versions
=> Upgrading interop libraries to alpha-20191220.1

samples/TerraFX/Graphics/HelloConstantBuffer.cs, samples/TerraFX/Graphics/HelloQuad.cs, samples/TerraFX/Program.cs, sources/Graphics/Assets/Shaders/TransformPixel.glsl, sources/Graphics/Assets/Shaders/TransformPixel.hlsl, sources/Graphics/Assets/Shaders/TransformTypes.hlsl, sources/Graphics/Assets/Shaders/TransformVertex.glsl, sources/Graphics/Assets/Shaders/TransformVertex.hlsl, sources/Graphics/GraphicsBufferKind.cs, sources/Graphics/GraphicsDevice.cs, sources/Graphics/GraphicsPipeline.cs, sources/Graphics/GraphicsPipelineInput.cs, sources/Graphics/GraphicsPipelineInputElement.cs, sources/Graphics/GraphicsPipelineResource.cs, sources/Graphics/GraphicsPipelineResourceKind.cs, sources/Graphics/GraphicsPipelineSignature.cs, sources/Graphics/GraphicsPrimitive.cs, sources/Graphics/GraphicsShaderVisibility.cs, sources/Graphics/TerraFX.Graphics.csproj, sources/Providers/Graphics/D3D12/D3D12GraphicsContext.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPipeline.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPipelineSignature.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPrimitive.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsBuffer.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsContext.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsDevice.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsPipeline.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsPipelineSignature.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsPrimitive.cs
This adds basic support for declaring, updating, and consuming constant/uniform buffers.
There needs to be a bit of cleanup with resource management and being able to schedule updates (rather than forcing it as part of the draw call).
=> Adding basic support for constant/uniform buffers

samples/TerraFX/Program.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsContext.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsDevice.cs
This changes the graphics device to no longer use SRGB by default, fixes the vulkan implementation by ensuring the VkDescriptorBufferInfo is correctly created, and ensures that all samples are enabled again.
=> Don't use SRGB, fix vulkan, and enable samples

sources/Providers/Graphics/Vulkan/VulkanGraphicsContext.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsPipeline.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsProvider.cs
This updates the Vulkan Provider to cull backfaces and to have the same origin as DirectX by default.
=> Updating the Vulkan Provider to cull and have the same origin as DirectX by default.

sources/Providers/Graphics/D3D12/D3D12GraphicsContext.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsDevice.cs
Not everything was being properly reset and so certain fields would be in an incorrect state. This looks to have occurred due to a previous refactoring.
=> Ensure that the GraphicsDevice and GraphicsDeviceContext properly update when the backing surface changes size

sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs
This can be removed once the memory allocator is rewritten.
=> Throw an exception if D3D12_RESOURCE_HEAP_TIER is not 2

.github/workflows/ci.yml
This should allow all nuget packages to be pushed, rather than just TerraFX
=> Quote the packages to push to avoid bash globbing

samples/TerraFX/Graphics/HelloConstantBuffer.cs, samples/TerraFX/Graphics/HelloQuad.cs, samples/TerraFX/Graphics/HelloTexture.cs, samples/TerraFX/Graphics/HelloTriangle.cs, samples/TerraFX/Graphics/HelloWindow.cs, samples/TerraFX/Program.cs, samples/TerraFX/Shared/Sample.cs, sources/Graphics/GraphicsPrimitive.cs, sources/Graphics/Memory/GraphicsMemoryAllocator.cs, sources/Graphics/Memory/GraphicsMemoryBlockCollection.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsBuffer.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsContext.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPrimitive.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsTexture.cs, sources/Providers/Graphics/D3D12/Memory/D3D12GraphicsMemoryAllocator.cs, sources/Providers/Graphics/Vulkan/Memory/VulkanGraphicsMemoryAllocator.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsBuffer.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsDevice.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsPrimitive.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsTexture.cs
A few dispose statements were missed for the new memory allocators, this adds them and ensures no diagnostics are reported on close.
=> Ensure that resources are properly cleaned up

samples/TerraFX/Graphics/HelloConstantBuffer.cs, samples/TerraFX/Graphics/HelloQuad.cs, samples/TerraFX/Graphics/HelloTexture.cs, samples/TerraFX/Graphics/HelloTriangle.cs, sources/Providers/Graphics/Vulkan/VulkanGraphicsProvider.cs, sources/Utilities/InteropUtilities.cs, sources/Utilities/ValueLazy`1.cs
`InteropUtilities.SkipInit` can be replaced with `Unsafe.SkipInit`. Also fixes several `(uint)sizeof` casts to use the `SizeOf<T>` helper method.
=> Cleaning up unnecessary InteropUtilities methods

sources/Core/Numerics/Vector3.cs, tests/Core/Numerics/Vector3Tests.cs
Fixes #100.
I've not vectorized these, and have instead only provided the software fallback, because I'm not sure I trust myself to correctly implement it. Plus, I believe there probably isn't much benefit to vectorizing *these* methods specifically, since they deal with small amounts of data - the overhead of shuffling data about would probably outweigh the performance benefits of vectorizing the code currently.
Maybe in the future we can add methods to take vectors in bulk to implement the vectorized versions of these algorithms.
Unit tests are in progress.
=> [IMPL] Add core Vector3 functionality

sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs
This should have been removed with #91 but was missed.
=> Removing the check enforcing the GPU support Resource Heap Tier 2

Directory.Build.targets, scripts/build.ps1, scripts/build.sh, sources/Core/Collections/NotifyCollectionChangedEventArgs`1.cs, sources/Core/Collections/NotifyDictionaryChangedEventArgs`2.cs, sources/Providers/Audio/PulseAudio/AudioProvider.cs, sources/Providers/Audio/PulseAudio/PulseAudioPlaybackDevice.cs, sources/Providers/UI/Win32/Win32WindowProvider.cs
This upgrades the repo to .NET 5 RC2. This allows us to simplify the `UnmanagedCallersOnly` usage sites by removing unnecessary casts and required some additional nullability annotations.
=> Upgrading to .NET 5 RC2

sources/Providers/Graphics/D3D12/Memory/D3D12GraphicsMemoryAllocator.cs
Textures were being created on the RT/DS heap which was causing issues on older GPUs without resource heap tier 2 support.
=> Ensure textures are created on the non RT/DS heap by default

sources/Providers/Graphics/Vulkan/Memory/VulkanGraphicsMemoryAllocator.cs
This ensures Vulkan works with a card that only supports "resource tier 1" for DirectX
=> Ensure we validate the memory type is compatible with the VkMemoryRequirements

sources/Providers/Graphics/D3D12/D3D12GraphicsTexture.cs
The logic for the D3D12GraphicsTexture was always setting the shader resource view to be 2D. This updates that logic to also support 1D and 3D.
=> Ensure that D3D12_SHADER_RESOURCE_VIEW_DESC correctly takes the GraphicsTextureKind into account

sources/Core/Numerics/Vector2.cs, tests/Core/Numerics/Vector2Tests.cs
Fixes #101.
Likewise with #109, this adds the core functionality and unit tests for Vector2. It's basically a direct copy+paste of the Vector3 code but with the 'Z' component removed.
In addition, I've also left out the single-parameter constructor for the same reason as in the Vector3 PR.
=> [IMPL] Add core Vector2 functionality

sources/Core/Numerics/Vector4.cs, tests/Core/Vector4Tests.cs
Fixes #99.
Again, as with #109 and #110, this is almost a direct copy+paste of the Vector3 code but with the 'W' component added. This adds the core functionality and unit tests for Vector4.
I've left out the single-parameter constructor again, for the same reasons as Vector3 and Vector2.
=> [IMPL] Add core Vector4 functionality

sources/Providers/Graphics/D3D12/D3D12GraphicsContext.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsDevice.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPipeline.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPipelineSignature.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsPrimitive.cs, sources/Providers/Graphics/D3D12/D3D12GraphicsTexture.cs
This updates how the `CbvSrvUavDescriptorHeap` is handled for D3D12. Previously, this heap was set per device but this greatly limits its reusability and will ultimately cause resources to overwrite eachother.
This PR changes it to be tracked per primitive instead so that resources don't overlap and the state can be tracked correctly for each shader. While still not an ideal setup and while it won't work quite correctly with instancing, it is a step in the right direction for now.
=> Updating how the CbvSrvUavDescriptorHeap is handled for D3D12

sources/Providers/UI/Win32/Win32Window.cs
This ensures resize and relocate can run successfully even before the first show and without computing the other at an incorrect location.
=> Updating Win32Window to cache the window size after creation

samples/TerraFX/Audio/EnumerateAudioAdapters.cs, samples/TerraFX/Audio/PlaySampleAudio.cs, samples/TerraFX/Graphics/HelloQuad.cs, samples/TerraFX/Graphics/HelloSierpinski.cs, samples/TerraFX/Graphics/HelloSmoke.cs, samples/TerraFX/Graphics/HelloTexture.cs, samples/TerraFX/Graphics/HelloTexture3D.cs, samples/TerraFX/Graphics/HelloTextureTransform.cs, samples/TerraFX/Graphics/HelloTransform.cs, samples/TerraFX/Graphics/HelloTriangle.cs, samples/TerraFX/Graphics/HelloWindow.cs, samples/TerraFX/Program.cs, samples/TerraFX/Shared/Sample.cs
Sample.Initialize() should take a timeout as parameter, such that Program.cs can set it to 2.5s when all samples are run, and to TimeSpan.MaxValue when only one is run.
=> [IMPL] Sample.Timeout

samples/TerraFX/Graphics/HelloWindow.cs
Any sample derived from `HelloWindow` should display the frame rate in the title. This info is already available in the `OnIdle` method. It just needs to be shown. The `Title` property should only be written to if the frame rate actually changed.
=> [IMPL] HelloWindow Title with frame rate

Directory.Build.props, Directory.Build.targets, samples/TerraFX/TerraFX.Samples.csproj, scripts/build.ps1, scripts/build.sh, sources/ApplicationModel/TerraFX.ApplicationModel.csproj, sources/Audio/Core/TerraFX.Audio.csproj, sources/Audio/PulseAudio/TerraFX.Audio.PulseAudio.csproj, sources/Core/TerraFX.csproj, sources/Graphics/Core/TerraFX.Graphics.csproj, sources/Graphics/D3D12/TerraFX.Graphics.D3D12.csproj, sources/Graphics/Vulkan/TerraFX.Graphics.Vulkan.csproj, sources/UI/Core/TerraFX.UI.csproj, sources/UI/Win32/TerraFX.UI.Win32.csproj, sources/UI/WinForms/TerraFX.UI.WinForms.csproj, sources/UI/Xlib/TerraFX.UI.Xlib.csproj, tests/ApplicationModel/TerraFX.ApplicationModel.UnitTests.csproj, tests/Audio/Core/TerraFX.Audio.UnitTests.csproj, tests/Audio/PulseAudio/TerraFX.Audio.PulseAudio.UnitTests.csproj, tests/Core/TerraFX.UnitTests.csproj, tests/Graphics/Core/TerraFX.Graphics.UnitTests.csproj, tests/Graphics/D3D12/TerraFX.Graphics.D3D12.UnitTests.csproj, tests/Graphics/Vulkan/TerraFX.Graphics.Vulkan.UnitTests.csproj, tests/UI/Core/TerraFX.UI.UnitTests.csproj, tests/UI/Win32/TerraFX.UI.Win32.UnitTests.csproj, tests/UI/WinForms/TerraFX.UI.WinForms.UnitTests.csproj, tests/UI/Xlib/TerraFX.UI.Xlib.UnitTests.csproj
This involves disabling trimming until the rewrite can occur
=> Remove net5.0 support and move forward to a net6.0 build without the breaking change

Directory.Build.props, Directory.Build.targets
This works around two minor issues when working with the latest .NET 7 SDK.
The former should be properly fixed via a `nuget.config` file and the latter will be fixed with .NET 7 RC1 when the `UnscopedRef` attribute support is available.
=> Work around NU1507 and the `langversion=latest` when targeting .NET 6 with a .NET 7 SDK issue
